# 基础

## 导包

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cpu


## Tensor

### 创建

#### tensor函数

PyTorch的tensors可以通过 `torch.tensor()`创建.

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### rand函数

为什么是随机张量? 随机张量之所以重要, 是因为许多神经网络的学习方式是从充满随机数的张量开始, 并调整这些随机数以更好地表示数据.

<div class="admonition tip">
    <p class="admonition-title">Tip</p>
    <p style="margin: 10px;">
        这个过程可以表达如下: 从随机数开始 -> 查看数据 -> 更新随机数 -> 查看数据 -> 更新随机数.
    </p>
</div>

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6117, 0.9745, 0.4607, 0.3245],
        [0.8630, 0.0838, 0.8136, 0.5270],
        [0.9186, 0.7397, 0.8897, 0.0694]])

In [19]:
random_tensor.dtype

torch.float32

In [20]:
# Create a random tensor with similar shape to run an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # Height, width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [21]:
torch.rand(size=(3, 3))

tensor([[0.7726, 0.7639, 0.7455],
        [0.4972, 0.7079, 0.7934],
        [0.4511, 0.8394, 0.9230]])

#### zeros/ones函数

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

#### arange函数

In [32]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### zeros_like函数

用于创建和`input`相同形状的零tensor

In [33]:
# Creating tensor zeros like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### ones_like函数

用于创建和`input`相同形状的一tensor.

In [34]:
# Creating tensor ones like
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### 数据类型

<div class="admonition note">
    <p class="admonition-title">笔记</p>
    <p style="margin: 10px">
        Tensor的数据类型是学习PyTorch和深度学习中的三大难点之一:
            <ul>
                <li> Tensor的数据累不正确
                <li> Tensor的形状不正确
                <li> Tensor的设备不正确
            </ul>
    </p>
</div>

In [41]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # Tensor的数据类型是什么
                               device="cpu", # Tensor运行的设备类型是什么
                               requires_grad=False # 是否跟踪该Tensor在后续操作中的梯度
                               )
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [43]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)