# 基础

## Import Packages

In [149]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cpu


## Tensor

### Creation

#### tensor function

PyTorch的tensors可以通过 `torch.tensor()`创建.

In [150]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [151]:
scalar.ndim

0

In [152]:
scalar.shape

torch.Size([])

In [153]:
# Get tensor back as Python int
scalar.item()

7

In [154]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [155]:
vector.ndim

1

In [156]:
vector.shape

torch.Size([2])

In [157]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [158]:
MATRIX.ndim

2

In [159]:
MATRIX[0]

tensor([7, 8])

In [160]:
MATRIX[1]

tensor([ 9, 10])

In [161]:
MATRIX.shape

torch.Size([2, 2])

In [162]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [163]:
TENSOR.ndim

3

In [164]:
TENSOR.shape

torch.Size([1, 3, 3])

In [165]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### rand function

为什么是随机张量? 随机张量之所以重要, 是因为许多神经网络的学习方式是从充满随机数的张量开始, 并调整这些随机数以更好地表示数据.

<div class="admonition tip">
    <p class="admonition-title">Tip</p>
    <p style="margin: 10px;">
        这个过程可以表达如下: 从随机数开始 -> 查看数据 -> 更新随机数 -> 查看数据 -> 更新随机数.
    </p>
</div>

In [166]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4869, 0.9509, 0.2692, 0.0772],
        [0.8947, 0.2129, 0.7935, 0.1830],
        [0.2059, 0.2288, 0.7810, 0.0554]])

In [167]:
random_tensor.dtype

torch.float32

In [168]:
# Create a random tensor with similar shape to run an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # Height, width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [169]:
torch.rand(size=(3, 3))

tensor([[0.0648, 0.3714, 0.8026],
        [0.4203, 0.0541, 0.2921],
        [0.4099, 0.8102, 0.9921]])

#### zeros/ones function

In [170]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [171]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [172]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [173]:
ones.dtype

torch.float32

#### arange function

In [174]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### zeros_like function

用于创建和`input`相同形状的零tensor

In [175]:
# Creating tensor zeros like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### ones_like function

用于创建和`input`相同形状的一tensor.

In [176]:
# Creating tensor ones like
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Datatype

<div class="admonition note">
    <p class="admonition-title">笔记</p>
    <p style="margin: 10px">
        Tensor的数据类型是学习PyTorch和深度学习中的三大难点之一:
            <ul>
                <li> Tensor的数据累不正确
                <li> Tensor的形状不正确
                <li> Tensor的设备不正确
            </ul>
    </p>
</div>

In [177]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # Tensor的数据类型是什么
                               device="cpu", # Tensor运行的设备类型是什么
                               requires_grad=False # 是否跟踪该Tensor在后续操作中的梯度
                               )
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [178]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [179]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [180]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [181]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Information Acquisition

In [182]:
random_tensor = torch.rand(3, 4)
# 获取数据类型信息, 获取形状信息, 获取设备信息
random_tensor.dtype, random_tensor.shape, random_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulation

Tensor操作包括:

- 加法
- 减法
- 乘法
- 除法
- 点积

In [183]:
tensor = torch.tensor([1, 2, 3])

#### Addition

In [184]:
tensor + 10, torch.add(tensor, 10)

(tensor([11, 12, 13]), tensor([11, 12, 13]))

#### Subtraction

In [185]:
tensor - 10

tensor([-9, -8, -7])

#### Multiplication

In [186]:
tensor * 10, torch.mul(tensor, 10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

#### Division

In [187]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

#### Dot Product

In [188]:
tensor_new = torch.tensor([2, 3, 4])
tensor_new @ tensor, torch.matmul(tensor, tensor_new)

(tensor(20), tensor(20))

PyTorch实现的点积较手动用for循环实现的快了不少:

In [189]:
%%time
value = 0
for i in range(3): 
    value += tensor[i] * tensor_new[i]
print(value)

tensor(20)
CPU times: user 1.73 ms, sys: 1 ms, total: 2.73 ms
Wall time: 2.12 ms


In [190]:
%%time
tensor_new @ tensor

CPU times: user 172 μs, sys: 99 μs, total: 271 μs
Wall time: 227 μs


tensor(20)

In [191]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[4, 5, 6], [7, 8, 9]])
tensor_A @ tensor_B

tensor([[18, 21, 24],
        [40, 47, 54],
        [62, 73, 84]])

In [192]:
%%capture
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
tensor_A @ tensor_B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [193]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]]).T
tensor_A @ tensor_B

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Aggregation

In [194]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [195]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [196]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [197]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [198]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [199]:
torch.argmin(x)

tensor(0)

In [200]:
torch.argmax(x)

tensor(9)