# 基础

## Import Packages

In [80]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cpu


In [81]:
import os
proxy = 'socks5://127.0.0.1:5353'
os.environ['http_proxy'] = proxy
os.environ['HTTP_PROXY'] = proxy
os.environ['https_proxy'] = proxy
os.environ['HTTPS_PROXY'] = proxy

## Tensor

### Creation

#### tensor function

PyTorch的tensors可以通过 `torch.tensor()`创建.

In [82]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [83]:
scalar.ndim

0

In [84]:
scalar.shape

torch.Size([])

In [85]:
# Get tensor back as Python int
scalar.item()

7

In [86]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [87]:
vector.ndim

1

In [88]:
vector.shape

torch.Size([2])

In [89]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [90]:
MATRIX.ndim

2

In [91]:
MATRIX[0]

tensor([7, 8])

In [92]:
MATRIX[1]

tensor([ 9, 10])

In [93]:
MATRIX.shape

torch.Size([2, 2])

In [94]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [95]:
TENSOR.ndim

3

In [96]:
TENSOR.shape

torch.Size([1, 3, 3])

In [97]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### rand function

为什么是随机张量? 随机张量之所以重要, 是因为许多神经网络的学习方式是从充满随机数的张量开始, 并调整这些随机数以更好地表示数据.

<div class="admonition tip">
    <p class="admonition-title">Tip</p>
    <p style="margin: 10px;">
        这个过程可以表达如下: 从随机数开始 -> 查看数据 -> 更新随机数 -> 查看数据 -> 更新随机数.
    </p>
</div>

In [98]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8409, 0.5176, 0.6005, 0.4054],
        [0.5673, 0.0546, 0.3773, 0.9264],
        [0.3422, 0.4428, 0.3592, 0.9739]])

In [99]:
random_tensor.dtype

torch.float32

In [100]:
# Create a random tensor with similar shape to run an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # Height, width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [101]:
torch.rand(size=(3, 3))

tensor([[0.6873, 0.9005, 0.6084],
        [0.6839, 0.8508, 0.0869],
        [0.1186, 0.9159, 0.3580]])

#### zeros/ones function

In [102]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [103]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [104]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [105]:
ones.dtype

torch.float32

#### arange function

In [106]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### zeros_like function

用于创建和`input`相同形状的零tensor

In [107]:
# Creating tensor zeros like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### ones_like function

用于创建和`input`相同形状的一tensor.

In [108]:
# Creating tensor ones like
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Datatype

<div class="admonition note">
    <p class="admonition-title">笔记</p>
    <p style="margin: 10px">
        Tensor的数据类型是学习PyTorch和深度学习中的三大难点之一:
            <ul>
                <li> Tensor的数据累不正确
                <li> Tensor的形状不正确
                <li> Tensor的设备不正确
            </ul>
    </p>
</div>

In [109]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # Tensor的数据类型是什么
                               device="cpu", # Tensor运行的设备类型是什么
                               requires_grad=False # 是否跟踪该Tensor在后续操作中的梯度
                               )
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [110]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [111]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [112]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [113]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Information Acquisition

In [114]:
random_tensor = torch.rand(3, 4)
# 获取数据类型信息, 获取形状信息, 获取设备信息
random_tensor.dtype, random_tensor.shape, random_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulation

Tensor操作包括:

- 加法
- 减法
- 乘法
- 除法
- 点积

In [115]:
tensor = torch.tensor([1, 2, 3])

#### Addition

In [116]:
tensor + 10, torch.add(tensor, 10)

(tensor([11, 12, 13]), tensor([11, 12, 13]))

#### Subtraction

In [117]:
tensor - 10

tensor([-9, -8, -7])

#### Multiplication

In [118]:
tensor * 10, torch.mul(tensor, 10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

#### Division

In [119]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

#### Dot Product

In [120]:
tensor_new = torch.tensor([2, 3, 4])
tensor_new @ tensor, torch.matmul(tensor, tensor_new)

(tensor(20), tensor(20))

PyTorch实现的点积较手动用for循环实现的快了不少:

In [121]:
%%time
value = 0
for i in range(3): 
    value += tensor[i] * tensor_new[i]
print(value)

tensor(20)
CPU times: user 0 ns, sys: 2.07 ms, total: 2.07 ms
Wall time: 1.47 ms


In [122]:
%%time
tensor_new @ tensor

CPU times: user 454 μs, sys: 74 μs, total: 528 μs
Wall time: 491 μs


tensor(20)

In [123]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[4, 5, 6], [7, 8, 9]])
tensor_A @ tensor_B

tensor([[18, 21, 24],
        [40, 47, 54],
        [62, 73, 84]])

In [124]:
%%capture
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
tensor_A @ tensor_B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [125]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]]).T
tensor_A @ tensor_B

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

#### Aggregation

In [126]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [127]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [128]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [129]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [130]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [131]:
torch.argmin(x)

tensor(0)

In [132]:
torch.argmax(x)

tensor(9)

#### Reshaping

In [133]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [134]:
%%capture
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [135]:
x_reshaped_1 = x.reshape(1, 9)
x_reshaped_2 = x.reshape(9, 1)
x_reshaped_1, x_reshaped_2, x_reshaped_1.ndim, x_reshaped_2.ndim, x.ndim

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 2,
 2,
 1)

In [136]:
x_reshaped_3 = x.reshape(3, 3)
x_reshaped_3, x_reshaped_3.ndim

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 2)

#### Stacking

In [137]:
x = torch.arange(1, 10)
x_stacked = torch.stack([x, x, x, x, x])
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [138]:
x_stacked_1 = torch.stack([x, x, x, x, x], dim=0)
x_stacked_1

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [139]:
x_stacked_2 = torch.stack([x, x, x, x, x], dim=1)
x_stacked_2

tensor([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9]])

#### Squeezing

把所有的形状为1为维度都给移除掉.

In [143]:
x = torch.arange(1, 10)
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([9]))

#### Unsqueezing

在原来的基础上在某一个位置添加一个维度.

In [148]:
x = torch.arange(1, 10)
x_reshaped = x.reshape(1, 9)
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_squeezed, x_unsqueezed, x_squeezed.shape, x_unsqueezed.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([9]),
 torch.Size([1, 9]))

In [149]:
x = torch.arange(1, 10)
x_reshaped = x.reshape(1, 9)
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_squeezed, x_unsqueezed, x_squeezed.shape, x_unsqueezed.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9]),
 torch.Size([9, 1]))

#### Permutation

更改维度的排列已改变形状, 返回的是一个视图.

In [151]:
x = torch.randn(2, 3, 5)
torch.permute(x, (2, 0, 1)).shape # 表示新的形状组成为(原先的第2个维度, 原先的第0个维度, 原先的第1个维度)

torch.Size([5, 2, 3])

In [154]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
x_permuted, x_permuted.shape

(tensor([[[0.0088, 0.8376, 0.0802,  ..., 0.6325, 0.0213, 0.2834],
          [0.3513, 0.1183, 0.7665,  ..., 0.9929, 0.8059, 0.1764],
          [0.9806, 0.1449, 0.9674,  ..., 0.9173, 0.2445, 0.0259],
          ...,
          [0.7870, 0.8730, 0.4487,  ..., 0.8504, 0.4603, 0.7921],
          [0.4887, 0.0125, 0.3125,  ..., 0.8557, 0.6070, 0.1941],
          [0.9150, 0.5267, 0.9130,  ..., 0.2542, 0.1025, 0.9944]],
 
         [[0.9795, 0.4907, 0.9462,  ..., 0.7371, 0.8396, 0.2591],
          [0.1745, 0.5976, 0.5650,  ..., 0.4565, 0.7162, 0.9631],
          [0.7069, 0.1519, 0.3868,  ..., 0.9886, 0.6089, 0.8145],
          ...,
          [0.2296, 0.8999, 0.2704,  ..., 0.8549, 0.7626, 0.0971],
          [0.7486, 0.5413, 0.0997,  ..., 0.4745, 0.5297, 0.7525],
          [0.4041, 0.0511, 0.4756,  ..., 0.7590, 0.1381, 0.5209]],
 
         [[0.4152, 0.6135, 0.3249,  ..., 0.8757, 0.2325, 0.9014],
          [0.0709, 0.2181, 0.9458,  ..., 0.2883, 0.8562, 0.9461],
          [0.6364, 0.1090, 0.8726,  ...,

### View

In [141]:
x = torch.arange(1, 10)
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [142]:
z[:, 0] = 10000000
z, x

(tensor([[10000000,        2,        3,        4,        5,        6,        7,
                 8,        9]]),
 tensor([10000000,        2,        3,        4,        5,        6,        7,
                8,        9]))